import { Flags } from '@oclif/core';
import { renderModelExport } from '@space-kraken/nebula-forge-core';
import { BaseCommand } from '../lib/base';
import { engineFor } from '../lib/engines';

export default class Model extends BaseCommand {
  static description =
    'Export the workspace model as versioned JSON for external tooling: rendered physical names (or the "autogenerated" marker), resolved tags, couplings and each component type\'s declared resource capabilities. Offline, no credentials.';

  static examples = ['forge model --json', 'forge model --json --env prod > model.json'];

  static flags = {
    json: Flags.boolean({
      description: 'emit JSON to stdout (the only format today; the flag keeps scripts explicit)',
      default: true,
      allowNo: false,
    }),
    env: Flags.string({ char: 'e', description: 'limit the export to one environment' }),
  };

  async run(): Promise<void> {
    const { flags } = await this.parse(Model);
    // warnings go to stderr (this.warn), so stdout stays parseable JSON
    const model = this.loadModel();
    const adapter = engineFor(model.engine);
    const exported = renderModelExport(model, adapter.capabilities, flags.env);
    this.log(JSON.stringify(exported, null, 2));
  }
}
