import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  COMPONENT_MANIFEST,
  ForgeError,
  isValidName,
  loadWorkspace,
  routePathIssues,
  toConstructId,
} from '@forgecli/core';
import { writeFile, writeJson, writeRendered } from './templates';

export const ENDPOINT_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
export type EndpointMethod = (typeof ENDPOINT_METHODS)[number];

const METHOD_DECORATORS: Record<EndpointMethod, string> = {
  GET: 'Get',
  POST: 'Post',
  PUT: 'Put',
  PATCH: 'Patch',
  DELETE: 'Delete',
};

export interface EndpointDef {
  name: string;
  method: EndpointMethod;
  route: string;
}

/**
 * Regenerates src/infrastructure/controllers/index.ts from the directory
 * listing. The barrel is fully owned by forge, so adding an endpoint never
 * requires fragile edits inside handwritten code.
 */
export function regenerateControllersBarrel(componentDir: string): void {
  const controllersDir = path.join(componentDir, 'src', 'infrastructure', 'controllers');
  const files = fs.existsSync(controllersDir)
    ? fs
        .readdirSync(controllersDir)
        .filter((file) => file.endsWith('.controller.ts'))
        .sort()
    : [];
  const entries = files.map((file) => {
    const base = file.slice(0, -'.controller.ts'.length);
    if (!isValidName(base)) {
      throw new ForgeError(
        `Controller file "${file}" does not follow the naming convention`,
        'Controllers must be <kebab-name>.controller.ts (no extra dots) exporting class <PascalName>Controller, so the generated barrel can register them.',
      );
    }
    const className = `${toConstructId(base)}Controller`;
    const source = fs.readFileSync(path.join(controllersDir, file), 'utf8');
    if (!source.includes(`export class ${className}`)) {
      throw new ForgeError(
        `Controller file "${file}" must export "class ${className}"`,
        'The generated barrel derives the class name from the file name — rename the file or the class so they match.',
      );
    }
    return { module: `./${base}.controller`, className };
  });
  const lines = [
    '// Generated by forge from the *.controller.ts files in this directory.',
    '// Do not edit — it is rewritten whenever forge adds an endpoint.',
    '// Convention: <kebab-name>.controller.ts exports class <PascalName>Controller.',
    ...entries.map((entry) => `import { ${entry.className} } from '${entry.module}';`),
    '',
    'export const controllers = [',
    ...entries.map((entry) => `  ${entry.className},`),
    '];',
    '',
  ];
  writeFile(path.join(controllersDir, 'index.ts'), lines.join('\n'));
}

export function endpointFiles(componentDir: string, name: string): { controller: string; useCase: string; test: string } {
  return {
    controller: path.join(componentDir, 'src', 'infrastructure', 'controllers', `${name}.controller.ts`),
    useCase: path.join(componentDir, 'src', 'application', `${name}.uc.ts`),
    test: path.join(componentDir, 'test', `${name}.test.ts`),
  };
}

export function validateEndpointDef(def: EndpointDef): void {
  if (!isValidName(def.name)) {
    throw new ForgeError(
      `Invalid endpoint name "${def.name}"`,
      'Endpoint names are kebab-case, e.g. "get-order" or "create-invoice".',
    );
  }
  if (!(ENDPOINT_METHODS as readonly string[]).includes(def.method)) {
    throw new ForgeError(`Invalid method "${def.method}" (allowed: ${ENDPOINT_METHODS.join(', ')})`);
  }
  const issues = routePathIssues(def.route);
  if (issues.length > 0) {
    throw new ForgeError(
      `Invalid route "${def.route}":\n  - ${issues.join('\n  - ')}`,
      'Routes use path segments like /orders, /orders/{id} or /files/{proxy+} (greedy segments go last).',
    );
  }
}

/** Writes controller + use case + test for one endpoint (no manifest changes). */
export function writeEndpointFiles(componentDir: string, def: EndpointDef): void {
  validateEndpointDef(def);
  const files = endpointFiles(componentDir, def.name);
  for (const file of Object.values(files)) {
    if (fs.existsSync(file)) {
      throw new ForgeError(`Endpoint "${def.name}" already exists (${file})`);
    }
  }
  const vars = {
    name: def.name,
    method: def.method,
    route: def.route,
    methodDecorator: METHOD_DECORATORS[def.method],
    className: `${toConstructId(def.name)}Controller`,
    ucClass: `${toConstructId(def.name)}UC`,
  };
  writeRendered(files.controller, 'component/endpoint/controller.ts.tpl', vars);
  writeRendered(files.useCase, 'component/endpoint/uc.ts.tpl', vars);
  writeRendered(files.test, 'component/endpoint/test.ts.tpl', vars);
}

/**
 * Attaches an endpoint to an existing http-api component: API Gateway route in
 * component.json + fusion controller + use case + test + regenerated barrel.
 * Rolls everything back if the resulting workspace does not validate.
 */
export function addEndpoint(root: string, moduleName: string, apiName: string, def: EndpointDef): void {
  validateEndpointDef(def);
  const componentDir = path.join(root, 'domains', moduleName, 'components', apiName);
  const manifestFile = path.join(componentDir, COMPONENT_MANIFEST);
  if (!fs.existsSync(manifestFile)) {
    throw new ForgeError(`Component "${moduleName}/${apiName}" does not exist`);
  }
  const before = fs.readFileSync(manifestFile, 'utf8');
  const manifest = JSON.parse(before) as Record<string, any>;
  if (manifest.type !== 'http-api') {
    throw new ForgeError(
      `Component "${moduleName}/${apiName}" is a ${manifest.type}, not an http-api`,
      'Endpoints attach to http-api components.',
    );
  }
  // Use the PARSED routes as the base: a manifest without a routes key serves
  // the schema default (ANY /{proxy+}), and dropping it here would silently
  // 404 every previously working path after the next deploy.
  const model = loadWorkspace(root);
  const spec = model.domains
    .find((domain) => domain.name === moduleName)
    ?.components.find((component) => component.name === apiName);
  const routes: { method: string; path: string }[] =
    spec?.type === 'http-api' ? spec.config.routes : (manifest.config?.routes ?? []);
  if (routes.some((route) => route.method === def.method && route.path === def.route)) {
    throw new ForgeError(`Route ${def.method} ${def.route} already exists on "${moduleName}/${apiName}"`);
  }

  writeEndpointFiles(componentDir, def);
  manifest.config = { ...(manifest.config ?? {}), routes: [...routes, { method: def.method, path: def.route }] };
  writeJson(manifestFile, manifest);
  regenerateControllersBarrel(componentDir);

  try {
    loadWorkspace(root);
  } catch (error) {
    fs.writeFileSync(manifestFile, before);
    for (const file of Object.values(endpointFiles(componentDir, def.name))) {
      fs.rmSync(file, { force: true });
    }
    regenerateControllersBarrel(componentDir);
    throw error;
  }
}
