import { ForgeError } from './errors';
import type { AnyComponentSpec, DomainSpec, WorkspaceModel } from './model';
import { renderTags, stackNameFor } from './names';

/**
 * Machine-readable model export (`forge model --json`): the workspace
 * contract for external tooling — IAM policy generators, convention
 * validators, platform inventories — without importing @forgecli/core.
 *
 * Versioning policy: `schemaVersion` starts at 1. Additive changes (new
 * optional fields) keep the version; renames or semantic changes bump it.
 * Physical-name coverage is DECLARED: resources forge does not name
 * deterministically export the literal marker "autogenerated" — never an
 * invented name.
 */
export const MODEL_SCHEMA_VERSION = 1;

export const AUTOGENERATED = 'autogenerated';

/**
 * What a CLI engine adapter declares about its engine, consumed by the model
 * export. Static metadata — no cloud calls, no credentials.
 */
export interface EngineCapabilityProvider {
  /** Infra resource types each component type MAY emit (CloudFormation or Terraform types). */
  components: Record<string, readonly string[]>;
  /** Domain-shared infra the engine provisions lazily (empty for engines without it). */
  domainShared?: readonly string[];
  /** Deterministic physical name, or undefined where the provider autogenerates. */
  physicalNameFor(
    model: WorkspaceModel,
    domain: DomainSpec,
    component: AnyComponentSpec,
    environment: string,
  ): string | undefined;
  /** The engine's own identity tags for a domain stack. */
  builtinTags(model: WorkspaceModel, domain: DomainSpec, environment: string): Record<string, string>;
}

export interface ExportedComponent {
  name: string;
  type: string;
  pack?: string;
  physicalName: string;
  capabilities: string[];
  bindings: { component: string; access: string }[];
  mount?: string;
  auth?: string;
  subscriptions?: unknown[];
  serves?: { api?: string; media?: string };
}

export interface ModelExport {
  schemaVersion: number;
  project: string;
  engine: string;
  conventions: string | null;
  naming: { pattern?: string; separator?: string } | null;
  domainShared: string[];
  environments: Record<
    string,
    {
      region: string;
      production: boolean;
      domains: {
        name: string;
        stack: string;
        tags: Record<string, string>;
        components: ExportedComponent[];
      }[];
    }
  >;
}

function exportComponent(
  model: WorkspaceModel,
  domain: DomainSpec,
  component: AnyComponentSpec,
  environment: string,
  provider: EngineCapabilityProvider,
): ExportedComponent {
  const exported: ExportedComponent = {
    name: component.name,
    type: component.type,
    physicalName: provider.physicalNameFor(model, domain, component, environment) ?? AUTOGENERATED,
    capabilities: [...(provider.components[component.type] ?? [])],
    bindings: component.bindings.map((binding) => ({ component: binding.component, access: binding.access })),
  };
  if ('pack' in component) {
    exported.pack = component.pack;
    return exported;
  }
  const config = component.config as Record<string, unknown>;
  if (typeof config.mount === 'string') exported.mount = config.mount;
  if (typeof config.auth === 'string') exported.auth = config.auth;
  if (Array.isArray(config.subscriptions) && config.subscriptions.length > 0) {
    exported.subscriptions = config.subscriptions;
  }
  if (component.type === 'static-site' && (config.api || config.media)) {
    exported.serves = {
      ...(typeof config.api === 'string' ? { api: config.api } : {}),
      ...(typeof config.media === 'string' ? { media: config.media } : {}),
    };
  }
  return exported;
}

export function renderModelExport(
  model: WorkspaceModel,
  provider: EngineCapabilityProvider,
  environment?: string,
): ModelExport {
  if (environment && !model.environments[environment]) {
    throw new ForgeError(
      `Environment "${environment}" is not declared in forge.json`,
      `Available environments: ${Object.keys(model.environments).join(', ')}`,
    );
  }
  const envNames = environment ? [environment] : Object.keys(model.environments);
  const environments: ModelExport['environments'] = {};
  for (const envName of envNames) {
    const envSpec = model.environments[envName];
    environments[envName] = {
      region: envSpec.region,
      production: envSpec.production ?? envName === 'prod',
      domains: model.domains.map((domain) => ({
        name: domain.name,
        stack: stackNameFor(model.name, domain.name, envName),
        tags: {
          ...provider.builtinTags(model, domain, envName),
          ...renderTags(model.tags, { project: model.name, module: domain.name, env: envName }),
        },
        components: [...domain.components, ...(domain.packComponents ?? [])].map((component) =>
          exportComponent(model, domain, component, envName, provider),
        ),
      })),
    };
  }
  return {
    schemaVersion: MODEL_SCHEMA_VERSION,
    project: model.name,
    engine: model.engine,
    conventions: model.conventions ?? null,
    naming: model.naming ?? null,
    domainShared: [...(provider.domainShared ?? [])],
    environments,
  };
}
