import { componentManifestSchema, configureNaming, renderModelExport } from '@forgecli/core';
import type { ComponentSpec, WorkspaceModel } from '@forgecli/core';
import * as path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { awsCdkEngine } from '../src/lib/engines/aws-cdk';
import { azureTerraformEngine } from '../src/lib/engines/azure-terraform';

const fixturesDir = path.join(__dirname, 'fixtures');
afterEach(() => configureNaming(undefined));

function component(raw: Record<string, unknown>): ComponentSpec {
  return { ...componentManifestSchema.parse(raw), path: fixturesDir } as ComponentSpec;
}

function makeModel(engine: 'aws-cdk' | 'azure-terraform'): WorkspaceModel {
  return {
    name: 'shop',
    engine,
    defaultEnvironment: 'dev',
    environments: { dev: { region: 'us-east-1' }, prod: { region: 'us-east-1', production: true } },
    tags: { 'cost-center': 'cc-1', app: '{project}' },
    root: fixturesDir,
    domains: [
      {
        name: 'billing',
        path: fixturesDir,
        components: [
          component({ name: 'api', type: 'function', config: { entry: 'handler.ts' } }),
          component({ name: 'files', type: 'bucket' }),
          component({ name: 'events', type: 'event-bus' }),
        ],
      },
    ],
  };
}

describe('renderModelExport', () => {
  it('exports versioned JSON: rendered names, autogenerated markers, tags and capabilities', () => {
    configureNaming(undefined);
    const exported = renderModelExport(makeModel('aws-cdk'), awsCdkEngine.capabilities, 'dev');

    expect(exported.schemaVersion).toBe(1);
    expect(exported.project).toBe('shop');
    expect(exported.conventions).toBeNull();
    expect(Object.keys(exported.environments)).toEqual(['dev']);

    const billing = exported.environments.dev.domains[0];
    expect(billing.stack).toBe('shop-billing-dev');
    expect(billing.tags).toMatchObject({
      'forge:app': 'shop',
      'forge:domain': 'billing',
      'forge:environment': 'dev',
      'cost-center': 'cc-1',
      app: 'shop',
    });

    const byName = Object.fromEntries(billing.components.map((c) => [c.name, c]));
    // name-addressed: rendered; bucket has no physical name: declared, not invented
    expect(byName.api.physicalName).toBe('shop-billing-api-dev');
    expect(byName.events.physicalName).toBe('shop-billing-events-dev');
    expect(byName.files.physicalName).toBe('autogenerated');
    expect(byName.api.capabilities).toContain('AWS::Lambda::Function');
    expect(byName.files.capabilities).toContain('AWS::S3::Bucket');
  });

  it('renders names with the workspace naming convention and rejects unknown environments', () => {
    const model = makeModel('aws-cdk');
    model.naming = { pattern: 'corp-{env}-{module}-{name}' };
    configureNaming(model.naming);
    const exported = renderModelExport(model, awsCdkEngine.capabilities);
    const byName = Object.fromEntries(
      exported.environments.dev.domains[0].components.map((c) => [c.name, c]),
    );
    expect(byName.api.physicalName).toBe('corp-dev-billing-api');
    expect(exported.naming?.pattern).toBe('corp-{env}-{module}-{name}');
    expect(() => renderModelExport(model, awsCdkEngine.capabilities, 'staging')).toThrow(/not declared/);
  });

  it('azure: function apps export the exact hashed-helper name, shared infra is declared', () => {
    configureNaming(undefined);
    const exported = renderModelExport(makeModel('azure-terraform'), azureTerraformEngine.capabilities, 'dev');
    const byName = Object.fromEntries(
      exported.environments.dev.domains[0].components.map((c) => [c.name, c]),
    );
    expect(byName.api.physicalName).toBe('fn-shop-billing-api-dev');
    expect(byName.events.physicalName).toBe('shop-billing-events-dev');
    expect(exported.domainShared).toContain('azurerm_resource_group');
    expect(exported.environments.dev.domains[0].tags['forge-app']).toBe('shop');
  });
});
