# {{name}}

AWS workspace generated with **forge**. The project structure, architecture and
wiring are managed by the CLI — you write the business logic.

## Structure

```
forge.json                     workspace manifest: engine + environments
domains/
  <module>/                    one business domain = one independent stack
    domain.json
    __tests__/infra.test.ts    infrastructure snapshot test for this module
    components/
      <component>/
        component.json         type, config and bindings
        src/                   only for components that run code
          handler.ts           composition root (wiring only)
          application/         use cases (business logic)
          domain/ports/        ports: interfaces the business logic depends on
          infrastructure/
            controllers/       http-api: one fusion controller per endpoint +
                               index.ts barrel regenerated by forge
            adapters/          driven adapters (repositories, clients)
        test/                  http-api: one test per endpoint;
                               function/queue-worker: handler.test.ts
docs/architecture.md           auto-generated architecture doc + Mermaid diagram
infra/app.ts                   CDK entry point (managed, no need to touch)
```

[docs/architecture.md](docs/architecture.md) is regenerated on every
`forge new` / `forge generate` (or on demand with `forge docs`), so the diagram
always matches the real architecture. It renders natively on GitHub/GitLab.

## Org naming & tag conventions (optional)

By default forge names resources `<project>-<module>-<component>-<env>`. When
your platform defines the contract (IAM deploy roles with name-prefix
conditions, mandatory tags), declare it in `forge.json` and forge conforms:

```jsonc
{
  "naming": {
    "pattern": "corp-{project}-{env}-{module}-{name}"  // tokens: {project} {module} {name} {env}
  },
  "tags": {
    "cost-center": "cc-1234",
    "owner": "platform-team",
    "app": "{project}",
    "stage": "{env}"                                   // tag values: {project} {module} {env}
  }
}
```

(`forge.json` is strict JSON — no comments; this block is the reference.)
Every name is rendered and validated when the workspace loads (charset,
length, collisions), and tags are applied to every resource by the engine.

> ⚠️ **Names are identity.** Changing `naming` on an already-deployed
> workspace REPLACES resources — for tables and buckets that means data loss.
> Pick the convention before the first deploy and treat it as frozen.

## Lambda conventions (hexagonal + fusion)

TypeScript lambdas follow hexagonal architecture on
[@fusion-framework/server](https://github.com/acyclicstudent/fusion-server):

- **Driving adapters** (HTTP controllers, SQS handlers) translate events into
  use-case executions — never put business logic in them.
- **Use cases** (`src/application`, `@UseCase()` classes run via `UCExecutor`)
  hold the business logic and depend only on **ports** (`src/domain/ports`).
- **Driven adapters** (`src/infrastructure/adapters`) implement ports against
  real services and are bound to their port token in `src/handler.ts`.
- Always inject with explicit tokens (`@Executor()`, `@Inject('token')`);
  esbuild does not emit decorator metadata, so injection by parameter type
  does not work at runtime.
- HTTP routing: fusion matches `httpMethod + resource` exactly, so controller
  decorators must mirror `config.routes` in component.json.
- SQS workers use a forge-generated adapter (not fusion listeners) so failed
  records are retried individually and reach the dead-letter queue.

Each module deploys as its own CloudFormation stack, so you can test and ship
one domain without touching the rest. Components inside a module connect
through **bindings** (`component.json`), which grant least-privilege IAM access
and inject discovery environment variables (e.g. `TABLE_DATA_NAME`,
`QUEUE_JOBS_URL`) into your handlers. Cross-domain integration should flow
through events, not direct bindings.

## Commands

```
forge list                                  show modules, components and bindings
forge docs [--print]                        regenerate docs/architecture.md (or print the diagram)
forge generate module <name>                add a domain (new stack)
forge generate component <name> \
  --module <m> --type http-api              add a component (interactive: forge infers and asks
                                            for attachments; flags: --bind/--attach/--subscribe)
forge generate endpoint <name> \
  --module <m> --method GET --route /x/{id} attach an endpoint to the module's API Lambda
forge attach <component> -m <m> \
  [--bind t:access] [--subscribe bus:...]   couple an existing component (interactive without flags)
forge detach <component> -m <m> \
  [--bind t] [--subscribe bus]              remove couplings (interactive without flags)
forge remove component <name> -m <m>        delete a component (refuses while referenced; --force detaches)
forge remove endpoint <name> -m <m>         delete an endpoint (route + controller + use case + test)
forge test [module] [--update]              run unit + infrastructure tests; --update accepts
                                            intentional infra changes (snapshot update)
forge diff [module] --env dev               preview changes
forge deploy <module> --env dev             deploy one domain
forge deploy --all --env dev                deploy everything (explicit)
```

Component types: `function`, `http-api`, `queue-worker`, `table`, `bucket`,
`topic`, `static-site`, `event-bus`.
Bindings: `--bind <component>:<access>` with `read`, `write`, `read-write` or
`publish`. Cross-domain bindings are allowed only to event buses
(`--bind other-domain/bus:publish`). Queue-workers and functions can subscribe
to buses (`--subscribe <bus>:source=…` or `config.subscriptions` in
component.json) — prefer a queue-worker when processing must be reliable
(retries + dead-letter queue); function subscriptions invoke the Lambda
directly.
