import * as fs from 'node:fs';
import { z } from 'zod';
import { ForgeError, loadWorkspace, renderModelExport } from '@forgecli/core';
import { attachBinding, attachSubscription, detachBinding, detachSubscription, parseAttaches, parseSubscribes } from '@forgecli/cli/dist/lib/attach';
import { writeArchitectureDocs } from '@forgecli/cli/dist/lib/docs';
import { addEndpoint } from '@forgecli/cli/dist/lib/endpoints';
import { engineFor } from '@forgecli/cli/dist/lib/engines';
import { removeComponent } from '@forgecli/cli/dist/lib/remove';
import { parseBindings, scaffoldComponent } from '@forgecli/cli/dist/lib/scaffold';

/**
 * forge's MCP tools: the same semantics as the CLI, always through the
 * NON-INTERACTIVE path (explicit parameters, no TTY, nothing can hang on a
 * prompt). Handlers are pure functions over an explicit workspaceRoot so
 * tests exercise them directly; the stdio transport lives in server.ts.
 * Mutating tools keep the CLI's transactionality: a failed call leaves the
 * workspace exactly as it was.
 */

export interface ForgeTool<Shape extends z.ZodRawShape = z.ZodRawShape> {
  name: string;
  description: string;
  schema: Shape;
  run(params: z.infer<z.ZodObject<Shape>>): Record<string, unknown>;
}

function tool<Shape extends z.ZodRawShape>(definition: ForgeTool<Shape>): ForgeTool<Shape> {
  return definition;
}

const workspaceRoot = z.string().describe('absolute path to the forge workspace (the directory with forge.json)');

export const listModel = tool({
  name: 'list_model',
  description:
    'Export the workspace model as versioned JSON: domains, components, rendered physical names (or "autogenerated"), resolved tags, couplings and capability manifests. Read-only.',
  schema: { workspaceRoot, env: z.string().optional().describe('limit to one environment') },
  run({ workspaceRoot: root, env }) {
    const model = loadWorkspace(root);
    return renderModelExport(model, engineFor(model.engine).capabilities, env) as unknown as Record<string, unknown>;
  },
});

export const validateWorkspace = tool({
  name: 'validate_workspace',
  description:
    'Load and fully validate the workspace (manifests, bindings, routes, naming, conventions). Returns the validation verdict and any load-time warnings. Read-only.',
  schema: { workspaceRoot },
  run({ workspaceRoot: root }) {
    const model = loadWorkspace(root);
    return {
      valid: true,
      project: model.name,
      engine: model.engine,
      domains: model.domains.map((domain) => ({
        name: domain.name,
        components: domain.components.length + (domain.packComponents?.length ?? 0),
      })),
      warnings: model.warnings ?? [],
    };
  },
});

export const generateComponent = tool({
  name: 'generate_component',
  description:
    'Create a component in a module (validated, transactional: on failure nothing is left behind). Couplings via bind ("target:access", the new component uses others), attach ("consumer:access", existing components use the new one) and subscribe ("bus:source=a,b" or "bus:detail-type=X").',
  schema: {
    workspaceRoot,
    module: z.string(),
    name: z.string(),
    type: z.string().describe('built-in component type or a pack-provided type'),
    config: z.record(z.unknown()).optional().describe('component.json config, validated by the loader'),
    bind: z.array(z.string()).optional(),
    attach: z.array(z.string()).optional(),
    subscribe: z.array(z.string()).optional(),
  },
  run({ workspaceRoot: root, module: moduleName, name, type, config, bind, attach, subscribe }) {
    const bindings = parseBindings(bind);
    const attaches = parseAttaches(attach);
    const subscriptions = parseSubscribes(subscribe);
    const merged = {
      ...(config ?? {}),
      ...(subscriptions.length > 0 ? { subscriptions } : {}),
    };
    const componentDir = scaffoldComponent(root, moduleName, {
      name,
      type: type as never,
      config: Object.keys(merged).length > 0 ? merged : undefined,
      bindings,
    });
    const attached: string[] = [];
    try {
      for (const entry of attaches) {
        attachBinding(root, moduleName, entry.consumer, { component: name, access: entry.access });
        attached.push(`${entry.consumer} → ${name} (${entry.access})`);
      }
    } catch (error) {
      // transactional: undo the scaffold so a corrected retry is not blocked
      fs.rmSync(componentDir, { recursive: true, force: true });
      writeArchitectureDocs(root);
      throw error;
    }
    writeArchitectureDocs(root);
    return {
      created: `${moduleName}/${name}`,
      type,
      files: [componentDir],
      attached,
      docsRegenerated: ['docs/architecture.md', 'AGENTS.md'],
    };
  },
});

export const generateEndpoint = tool({
  name: 'generate_endpoint',
  description:
    'Add an endpoint to a module http-api: the API Gateway route in component.json plus the controller, use case and test, always in sync (the controllers barrel is regenerated).',
  schema: {
    workspaceRoot,
    module: z.string(),
    api: z.string().describe('the http-api component that owns the endpoint'),
    name: z.string(),
    method: z.string().describe('GET, POST, PUT, PATCH, DELETE or ANY'),
    route: z.string().describe('route path, e.g. /users/{id}'),
    public: z.boolean().optional().describe('skip the authorizer for this route'),
  },
  run({ workspaceRoot: root, module: moduleName, api, name, method, route, public: isPublic }) {
    const normalized = method.toUpperCase();
    const allowed = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
    if (!(allowed as readonly string[]).includes(normalized)) {
      throw new ForgeError(`Invalid method "${method}"`, `Endpoints accept: ${allowed.join(', ')}.`);
    }
    addEndpoint(root, moduleName, api, {
      name,
      method: normalized as (typeof allowed)[number],
      route,
      public: isPublic,
    });
    writeArchitectureDocs(root);
    return { endpoint: `${normalized} ${route}`, api: `${moduleName}/${api}`, name };
  },
});

export const attachTool = tool({
  name: 'attach',
  description:
    'Attach couplings to an EXISTING component: bindings ("target:access") and/or event-bus subscriptions ("bus:source=a,b"). Validated with rollback on failure.',
  schema: {
    workspaceRoot,
    module: z.string(),
    component: z.string(),
    bind: z.array(z.string()).optional(),
    subscribe: z.array(z.string()).optional(),
  },
  run({ workspaceRoot: root, module: moduleName, component, bind, subscribe }) {
    const results: string[] = [];
    for (const binding of parseBindings(bind)) {
      const added = attachBinding(root, moduleName, component, binding);
      results.push(`${added ? 'bound' : 'already bound'}: ${component} → ${binding.component} (${binding.access})`);
    }
    for (const subscription of parseSubscribes(subscribe)) {
      const added = attachSubscription(root, moduleName, component, subscription);
      results.push(`${added ? 'subscribed' : 'already subscribed'}: ${component} ⇐ ${subscription.bus}`);
    }
    if (results.length === 0) {
      throw new ForgeError('Nothing to attach', 'Pass bind ("target:access") and/or subscribe ("bus:source=a,b") entries.');
    }
    writeArchitectureDocs(root);
    return { component: `${moduleName}/${component}`, changes: results };
  },
});

export const detachTool = tool({
  name: 'detach',
  description: 'Detach couplings from a component: bindings by target name and/or subscriptions by bus reference.',
  schema: {
    workspaceRoot,
    module: z.string(),
    component: z.string(),
    bind: z.array(z.string()).optional().describe('binding targets to remove, e.g. ["data"]'),
    subscribe: z.array(z.string()).optional().describe('bus references to unsubscribe, e.g. ["platform/events"]'),
  },
  run({ workspaceRoot: root, module: moduleName, component, bind, subscribe }) {
    const changes: string[] = [];
    for (const target of bind ?? []) {
      if (detachBinding(root, moduleName, component, target)) changes.push(`unbound: ${target}`);
    }
    for (const bus of subscribe ?? []) {
      if (detachSubscription(root, moduleName, component, bus)) changes.push(`unsubscribed: ${bus}`);
    }
    if ((bind ?? []).length === 0 && (subscribe ?? []).length === 0) {
      throw new ForgeError('Nothing to detach', 'Pass bind (target names) and/or subscribe (bus references).');
    }
    writeArchitectureDocs(root);
    return { component: `${moduleName}/${component}`, changes };
  },
});

export const removeComponentTool = tool({
  name: 'remove_component',
  description:
    'Remove a component. Refuses while other components reference it unless force=true, which detaches every referrer first so no dangling reference survives.',
  schema: {
    workspaceRoot,
    module: z.string(),
    component: z.string(),
    force: z.boolean().optional().describe('cascade-detach referrers before removing'),
  },
  run({ workspaceRoot: root, module: moduleName, component, force }) {
    const detachedReferrers = removeComponent(root, moduleName, component, { force: force ?? false });
    writeArchitectureDocs(root);
    return {
      removed: `${moduleName}/${component}`,
      detached: detachedReferrers.map((referrer) => `${referrer.domain}/${referrer.component} (${referrer.kind})`),
    };
  },
});

export const regenerateDocs = tool({
  name: 'regenerate_docs',
  description: 'Regenerate docs/architecture.md (Markdown + Mermaid) and AGENTS.md from the current model.',
  schema: { workspaceRoot },
  run({ workspaceRoot: root }) {
    writeArchitectureDocs(root);
    return { written: ['docs/architecture.md', 'AGENTS.md'] };
  },
});

export const FORGE_TOOLS = [
  listModel,
  validateWorkspace,
  generateComponent,
  generateEndpoint,
  attachTool,
  detachTool,
  removeComponentTool,
  regenerateDocs,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
] as ForgeTool<any>[];
