import * as fs from 'node:fs';
import * as path from 'node:path';
import { builtinTagsFor, ForgeError, FUNCTION_LIKE_TYPES, resourceNameFor, stackNameFor } from '@space-kraken/nebula-forge-core';
import type { EngineCapabilityProvider, WorkspaceModel } from '@space-kraken/nebula-forge-core';
import { runInWorkspace, runInWorkspaceRetrying } from '../proc';
import { writeCredentialSetting } from '../state';
import type { EngineAdapter } from './index';

/** The environment's named profile, exported so cdk and the SDK pick it up. */
function profileEnv(model: WorkspaceModel, environment: string): Record<string, string> {
  const profile = model.environments[environment]?.profile;
  return profile ? { AWS_PROFILE: profile } : {};
}

function runCdk(model: WorkspaceModel, environment: string, args: string[]): number {
  return runInWorkspace(model.root, 'npx', ['cdk', ...args], environment, profileEnv(model, environment));
}

/**
 * Windows race: Defender/indexers hold freshly written bundle files while
 * AssetStaging renames its temp dir → intermittent EBUSY on an otherwise
 * healthy synth. Bundling happens before CloudFormation is touched, so a
 * retry is always safe — including for deploy.
 */
const STAGING_EBUSY = /EBUSY: resource busy or locked/;

function runCdkRetrying(model: WorkspaceModel, environment: string, args: string[]): Promise<number> {
  return runInWorkspaceRetrying(model.root, 'npx', ['cdk', ...args], environment, profileEnv(model, environment), {
    pattern: STAGING_EBUSY,
    attempts: 3,
    delayMs: (attempt) => attempt * 1500,
    onRetry: (nextAttempt, total) =>
      console.error(
        `forge: a file lock (EBUSY) interrupted asset staging — retrying (attempt ${nextAttempt}/${total})…`,
      ),
  });
}

function stackNames(model: WorkspaceModel, environment: string, domains: string[]): string[] {
  return domains.map((domain) => stackNameFor(model.name, domain, environment));
}

/** Bootstrap stack name for a custom qualifier (the default qualifier keeps cdk's "CDKToolkit"). */
export function toolkitStackNameFor(qualifier: string): string {
  return `CDKToolkit-${qualifier}`;
}

/**
 * `cdk bootstrap` argv, honoring the environment's deploy identity block:
 * qualifier, permissions boundary (managed policy NAME) and CloudFormation
 * execution policies. A custom qualifier also names its bootstrap stack
 * (CDKToolkit-<qualifier>): several environments sharing one account each
 * get their own stack instead of the second bootstrap overwriting the
 * first's "CDKToolkit". Deploy never needs the name — the synthesizer
 * locates the bootstrap through the /cdk-bootstrap/<qualifier>/version SSM
 * parameter. Without the block, byte-identical to the plain call.
 * Exported for tests.
 */
export function bootstrapArgs(model: WorkspaceModel, environment: string): string[] {
  const envSpec = model.environments[environment];
  const args = ['cdk', 'bootstrap'];
  if (envSpec.account) args.push(`aws://${envSpec.account}/${envSpec.region}`);
  const deploy = envSpec.deploy;
  if (deploy?.qualifier) {
    args.push('--qualifier', deploy.qualifier, '--toolkit-stack-name', toolkitStackNameFor(deploy.qualifier));
  }
  if (deploy?.permissionsBoundary) args.push('--custom-permissions-boundary', deploy.permissionsBoundary);
  for (const policy of deploy?.executionPolicies ?? []) {
    args.push('--cloudformation-execution-policies', policy);
  }
  return args;
}

/** Deploying an unbuilt static-site would ship an empty 403-ing site — refuse. */
export function assertStaticSourcesBuilt(model: WorkspaceModel, domains: string[]): void {
  for (const domain of model.domains) {
    if (!domains.includes(domain.name)) continue;
    for (const component of domain.components) {
      if (component.type !== 'static-site') continue;
      const sourceDir = path.join(component.path, component.config.sourceDir);
      if (!fs.existsSync(sourceDir)) {
        throw new ForgeError(
          `Cannot deploy "${domain.name}": static-site "${component.name}" has no build at "${component.config.sourceDir}"`,
          `Build the frontend first (e.g. cd ${path.relative(model.root, component.path)}/app && pnpm install && pnpm build).`,
        );
      }
    }
  }
}

/**
 * Decorative physical names (addressed by id/Ref, never by name): rendered
 * only when they fit the service limit, autogenerated otherwise. Mirrors
 * decorativeName() in engine-cdk/src/builders.ts.
 */
const DECORATIVE_NAME_LIMITS: Record<string, number> = {
  'http-api': 128,
  gateway: 128,
  table: 255,
  auth: 128,
};

const LAMBDA_BASE = ['AWS::Lambda::Function', 'AWS::IAM::Role', 'AWS::IAM::Policy'];
const REST_API_BASE = [
  'AWS::ApiGateway::RestApi',
  'AWS::ApiGateway::Deployment',
  'AWS::ApiGateway::Stage',
  'AWS::ApiGateway::Resource',
  'AWS::ApiGateway::Method',
  'AWS::ApiGateway::Authorizer',
  'AWS::Lambda::Permission',
];
const API_DOMAIN_EXTRAS = [
  'AWS::CertificateManager::Certificate',
  'AWS::ApiGateway::DomainName',
  'AWS::ApiGateway::BasePathMapping',
  'AWS::Route53::RecordSet',
];

/** CloudFormation types each builder MAY emit — asserted against real synth output. */
const AWS_CAPABILITIES: EngineCapabilityProvider['components'] = {
  function: [...LAMBDA_BASE, 'AWS::Events::Rule', 'AWS::Lambda::Permission'],
  'http-api': [...LAMBDA_BASE, ...REST_API_BASE, ...API_DOMAIN_EXTRAS],
  gateway: [...REST_API_BASE, ...API_DOMAIN_EXTRAS],
  'queue-worker': [
    ...LAMBDA_BASE,
    'AWS::SQS::Queue',
    'AWS::SQS::QueuePolicy',
    'AWS::Lambda::EventSourceMapping',
    'AWS::Events::Rule',
  ],
  table: ['AWS::DynamoDB::Table'],
  bucket: ['AWS::S3::Bucket', 'AWS::S3::BucketPolicy', 'Custom::S3AutoDeleteObjects', ...LAMBDA_BASE],
  topic: ['AWS::SNS::Topic'],
  'static-site': [
    'AWS::S3::Bucket',
    'AWS::S3::BucketPolicy',
    'Custom::S3AutoDeleteObjects',
    'AWS::CloudFront::Distribution',
    'AWS::CloudFront::Function',
    'AWS::CloudFront::OriginAccessControl',
    'AWS::WAFv2::WebACL',
    'AWS::CertificateManager::Certificate',
    'AWS::Route53::RecordSet',
    'Custom::CDKBucketDeployment',
    'AWS::Lambda::LayerVersion',
    ...LAMBDA_BASE,
  ],
  'event-bus': ['AWS::Events::EventBus'],
  auth: ['AWS::Cognito::UserPool', 'AWS::Cognito::UserPoolClient'],
  email: ['AWS::SES::EmailIdentity'],
};

const awsCapabilityProvider: EngineCapabilityProvider = {
  components: AWS_CAPABILITIES,
  domainShared: [],
  physicalNameFor(model, domain, component, environment) {
    if ('pack' in component) return undefined;
    const rendered = resourceNameFor(model.name, domain.name, component.name, environment);
    // name-addressed: always set (the loader guarantees the limit)
    if ((FUNCTION_LIKE_TYPES as readonly string[]).includes(component.type) || component.type === 'event-bus') {
      return rendered;
    }
    const limit = DECORATIVE_NAME_LIMITS[component.type];
    if (limit) return rendered.length <= limit ? rendered : undefined;
    return undefined;
  },
  builtinTags(model, domain, environment) {
    return builtinTagsFor(
      { app: 'forge:app', domain: 'forge:domain', environment: 'forge:environment' },
      model.tags,
      { app: model.name, domain: domain.name, environment },
    );
  },
};

export const awsCdkEngine: EngineAdapter = {
  id: 'aws-cdk',
  enginePackage: 'engine-cdk',
  unsupportedTypes: [],
  capabilities: awsCapabilityProvider,
  workspaceFiles: [
    { template: 'engines/aws-cdk/forge.json.tpl', target: 'forge.json' },
    { template: 'engines/aws-cdk/package.json.tpl', target: 'package.json' },
    { template: 'engines/aws-cdk/cdk.json', target: 'cdk.json' },
    { template: 'engines/aws-cdk/gitignore', target: '.gitignore' },
    { template: 'engines/aws-cdk/infra/app.ts', target: 'infra/app.ts' },
  ],
  moduleTestTemplate: 'engines/aws-cdk/infra.test.ts.tpl',
  bootstrap: (model, environment, log) => {
    // CDK owns its state (CloudFormation); bootstrap provisions the assets
    // bucket and roles cdk deploy needs, once per account/region.
    const envSpec = model.environments[environment];
    log(`Bootstrapping AWS environment "${environment}" (region ${envSpec.region}) via cdk bootstrap…`);
    return runInWorkspace(model.root, 'npx', bootstrapArgs(model, environment), environment, {
      CDK_DEFAULT_REGION: envSpec.region,
      ...profileEnv(model, environment),
    });
  },
  credentials: {
    flag: 'profile',
    promptMessage: 'AWS profile for deployments (empty = default credentials):',
    write: (root, value) => writeCredentialSetting(root, 'profile', value),
  },
  runtimes: ['ts-fusion', 'ts'],
  defaultRuntime: 'ts-fusion',
  componentFiles: (type, runtime) => {
    switch (type) {
      case 'http-api':
        return [{ template: `component/http-api/${runtime}/handler.ts.tpl`, target: () => 'src/handler.ts' }];
      case 'queue-worker':
        return [
          { template: `component/queue-worker/${runtime}/handler.ts.tpl`, target: () => 'src/handler.ts' },
          {
            template: `component/queue-worker/${runtime}/process-message.uc.ts.tpl`,
            target: () => 'src/application/process-message.uc.ts',
          },
          {
            template: `component/queue-worker/${runtime}/message-store.port.ts.tpl`,
            target: () => 'src/domain/ports/message-store.ts',
          },
          {
            template: `component/queue-worker/${runtime}/console-message-store.adapter.ts.tpl`,
            target: () => 'src/infrastructure/adapters/console-message-store.ts',
          },
          { template: `component/queue-worker/${runtime}/handler.test.ts.tpl`, target: () => 'test/handler.test.ts' },
        ];
      case 'function':
        return [
          { template: `component/function/${runtime}/handler.ts.tpl`, target: () => 'src/handler.ts' },
          { template: `component/function/${runtime}/run-task.uc.ts.tpl`, target: () => 'src/application/run-task.uc.ts' },
          { template: `component/function/${runtime}/handler.test.ts.tpl`, target: () => 'test/handler.test.ts' },
        ];
      case 'static-site':
        return [{ template: 'component/static-site/index.html.tpl', target: () => 'site/index.html' }];
      default:
        return [];
    }
  },
  synth: (model, environment, domains) =>
    runCdkRetrying(model, environment, ['synth', ...stackNames(model, environment, domains)]),
  diff: (model, environment, domains) =>
    runCdkRetrying(model, environment, ['diff', ...stackNames(model, environment, domains)]),
  deploy: (model, environment, domains, options) => {
    assertStaticSourcesBuilt(model, domains);
    return runCdkRetrying(model, environment, [
      'deploy',
      ...stackNames(model, environment, domains),
      ...(options.skipApproval ? ['--require-approval', 'never'] : []),
    ]);
  },
};
